import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import AppProvider from "./app-provider";
import { cookies } from "next/headers";
import profileApiRequest from "./apiRequest/profile";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Laundry management app",
  description: "Generated by MillionLee",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const sessionToken = cookieStore.get("sessionToken");
  let user = null;
  if (sessionToken) {
    const data = await profileApiRequest.profile(sessionToken);
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <AppProvider initialSessionToken={sessionToken?.value}>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
