import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import AppProvider from "./app-provider";
import { cookies } from "next/headers";
import profileApiRequest from "./apiRequest/profile";
import {
  CustomerResType,
  RoleResType,
  StaffResType,
} from "./schemaValidations/auth.schema";
import authApiRequest from "./apiRequest/auth";
import HeaderAdmin from "@/components/HeaderAdmin";
import DefaultLayout from "@/components/DefaultLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Laundry management app",
  description: "Generated by MillionLee",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const sessionToken = cookieStore.get("sessionToken");
  type CustomerDataType = CustomerResType["data"];
  type StaffDataType = StaffResType["data"];
  let user: CustomerDataType | StaffDataType | null = null;
  // if (sessionToken) {
  //   const data = await profileApiRequest.profile(sessionToken);
  // }
  const username = cookieStore.get("username");

  let isStaff = false;
  if (username && sessionToken) {
    try {
      const roleData = await authApiRequest.roleid(
        username.value,
        sessionToken.value
      );

      if (roleData) {
        if (roleData.payload.data === 1) {
          const result = await profileApiRequest.customerProfile(
            username.value,
            sessionToken.value
          );

          user = result.payload.data;
        } else {
          const result = await profileApiRequest.staffProfile(
            username.value,
            sessionToken.value
          );
          user = result.payload.data;
          isStaff = true;
        }
      }
    } catch (error) {
      console.error("An error occurred:", error);
      // Nếu muốn xử lý lỗi cụ thể hơn, có thể kiểm tra lỗi và in ra các thông tin chi tiết
      if (error instanceof Error) {
        console.error("Error message:", error.message);
        console.error("Stack trace:", error.stack);
      } else {
        console.error("Unknown error:", error);
      }
    }
  }

  if (isStaff) {
    return (
      <html lang="en">
        <body className={inter.className}>
          <AppProvider initialSessionToken={sessionToken?.value} user={user}>
            <DefaultLayout user={user}>{children}</DefaultLayout>
          </AppProvider>
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider initialSessionToken={sessionToken?.value} user={user}>
          <Header user={user} />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
